package com.test.materialdesigndemo;


public interface Constants {

    String NAV_DRAWER_BROADCAST_RECEIVER = "NAV_DRAWER_ITEM_CLICKED";
    int READ_PHONE_STATE_PERMISSION_ID = 100;
    int TYPE_HEADER = 0;
    int TYPE_LIST = 1;
    String TAG_PRIORITY_NOTIFICATION = "PRIORITY_NOTIFICATION";
    String TAG_ACTIONABLE_NOTIFICATION = "ACTIONABLE_NOTIFICATION";
    String TAG_EXPANDED_NOTIFICATION = "EXPANDED_NOTIFICATION";
}
