package com.test.materialdesigndemo;


public interface Constants {

    String NAV_DRAWER_BROADCAST_RECEIVER = "NAV_DRAWER_ITEM_CLICKED";
    int READ_PHONE_STATE_PERMISSION_ID = 100;
    int TYPE_HEADER = 0;
    int TYPE_LIST = 1;
    int TAG_INBOX_STYLE_NOTIFICATION = 10;
    int TAG_BIG_TEXT_STYLE_NOTIFICATION = 11;
    int TAG_BIG_PICTURE_STYLE_NOTIFICATION = 12;
    int TAG_STACKED_STYLE_NOTIFICATION = 13;
}
